sudo: required
dist: trusty
language: node_js
node_js:
  - "0.12"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install php5-cli -y
  - yarn global add grunt-cli
  - php composer-install.php && php composer.phar install && rm composer.phar