version: '3.1'

services:
  web:
    image: anime-bracket
    ports:
      - '8080:80'
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./db/data:/var/lib/mysql
